[View in Colaboratory](https://colab.research.google.com/github/spiralspectra/AUAISummer2018/blob/master/project%20redone.ipynb)

In [4]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.

In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

In [0]:
import pandas as pd

df= pd.read_csv('drive/kayos-src/abc.csv')

In [7]:
df.head()

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1

In [0]:
df['Gender']=df['Gender'].replace({'Male':1,'Female':2})

In [11]:
df.head()

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,2,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,1,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,1,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,1,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,1,3.9,2.0,195,27,59,7.3,2.4,0.40,1

In [0]:
df['Dataset']=df['Dataset'].replace({2:0})

In [13]:
df

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,2,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,1,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,1,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,1,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,1,3.9,2.0,195,27,59,7.3,2.4,0.40,1
5,46,1,1.8,0.7,208,19,14,7.6,4.4,1.30,1
6,26,2,0.9,0.2,154,16,12,7.0,3.5,1.00,1
7,29,2,0.9,0.3,202,14,11,6.7,3.6,1.10,1
8,17,1,0.9,0.3,202,22,19,7.4,4.1,1.20,0
9,55,1,0.7,0.2,290,53,58,6.8,3.4,1.00,1
10,57,1,0.6,0.1,210,51,59,5.9,2.7,0.80,1
11,72,1,2.7,1.3,260,31,56,7.4,3.0,0.60,1
12,64,1,0.9,0.3,310,61,58,7.0,3.4,0.90,0
13,74,2,1.1,0.4,214,22,30,8.1,4.1,1.00,1
14,61,1,0.7,0.2,145,53,41,5.8,2.7,0.87,1
15,25,1,0.6,0.1,183,91,53,5.5,2.3,0.70,0
16,38,1,1.8,0.8,342,168,441,7.6,4.4,1.30,1
17,33,1,1.6,0.5,165,15,23,7.3,3.5,0.92,0
18,40,2,0.9,0.3,293,232,245,6.8,3.1,0.80,1
19,40,2,0.9,0.3,293,232,245,6.8,3.1,0.80,1
20,51,1,2.2,1.0,610,17,28,7.3,2.6,0.55,1
21,51,1,2.9,1.3,482,22,34,7.0,2.4,0.50,1
22,62,1,6.8,3.0,542,116,66,6.4,3.1,0.90,1
23,40,1,1.9,1.0,231,16,55,4.3,1.6,0.60,1
24,63,1,0.9,0.2,194,52,45,6.0,3.9,1.85,0
25,34,1,4.1,2.0,289,875,731,5.0,2.7,1.10,1
26,34,1,4.1,2.0,289,875,731,5.0,2.7,1.10,1
27,34,1,6.2,3.0,240,1680,850,7.2,4.0,1.20,1
28,20,1,1.1,0.5,128,20,30,3.9,1.9,0.95,0
29,84,2,0.7,0.2,188,13,21,6.0,3.2,1.10,0
...,...,...,...,...,...,...,...,...,...,...,...
553,46,1,10.2,4.2,232,58,140,7.0,2.7,0.60,1
554,73,1,1.8,0.9,220,20,43,6.5,3.0,0.80,1
555,55,1,0.8,0.2,290,139,87,7.0,3.0,0.70,1
556,51,1,0.7,0.1,180,25,27,6.1,3.1,1.00,1
557,51,1,2.9,1.2,189,80,125,6.2,3.1,1.00,1
558,51,1,4.0,2.5,275,382,330,7.5,4.0,1.10,1
559,26,1,42.8,19.7,390,75,138,7.5,2.6,0.50,1
560,66,1,15.2,7.7,356,321,562,6.5,2.2,0.40,1
561,66,1,16.6,7.6,315,233,384,6.9,2.0,0.40,1
562,66,1,17.3,8.5,388,173,367,7.8,2.6,0.50,1
563,64,1,1.4,0.5,298,31,83,7.2,2.6,0.50,1
564,38,2,0.6,0.1,165,22,34,5.9,2.9,0.90,0
565,43,1,22.5,11.8,143,22,143,6.6,2.1,0.46,1
566,50,2,1.0,0.3,191,22,31,7.8,4.0,1.00,0
567,52,1,2.7,1.4,251,20,40,6.0,1.7,0.39,1
568,20,2,16.7,8.4,200,91,101,6.9,3.5,1.02,1
569,16,1,7.7,4.1,268,213,168,7.1,4.0,1.20,1
570,16,1,2.6,1.2,236,131,90,5.4,2.6,0.90,1
571,90,1,1.1,0.3,215,46,134,6.9,3.0,0.70,1
572,32,1,15.6,9.5,134,54,125,5.6,4.0,2.50,1
573,32,1,3.7,1.6,612,50,88,6.2,1.9,0.40,1
574,32,1,12.1,6.0,515,48,92,6.6,2.4,0.50,1
575,32,1,25.0,13.7,560,41,88,7.9,2.5,2.50,1
576,32,1,15.0,8.2,289,58,80,5.3,2.2,0.70,1
577,32,1,12.7,8.4,190,28,47,5.4,2.6,0.90,1
578,60,1,0.5,0.1,500,20,34,5.9,1.6,0.37,0
579,40,1,0.6,0.1,98,35,31,6.0,3.2,1.10,1
580,52,1,0.8,0.2,245,48,49,6.4,3.2,1.00,1
581,31,1,1.3,0.5,184,29,32,6.8,3.4,1.00,1
582,38,1,1.0,0.3,216,21,24,7.3,4.4,1.50,0

In [0]:
import numpy as np
df = df.replace('?', np.nan)
df = df.dropna()


X = df.drop('Dataset', axis=1)
y = df[['Dataset']]


from sklearn.model_selection import train_test_split

# Split X and y into X_
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=1)

#SVM

In [0]:
from sklearn.svm import SVC

model = SVC(kernel='rbf', C=1, gamma=0.001, random_state=1)

In [20]:
model.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=1, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
from sklearn.metrics import accuracy_score

y_predict = model.predict(X_test)
score = accuracy_score(y_test, y_predict)
score

0.7068965517241379

In [25]:
model.predict([[34, 	1, 	20.2, 	3.2, 	132, 	28, 	240 ,	6.0 ,	2.1 	,0.43 	]])

array([1])

#logistic regression

In [22]:
from sklearn.linear_model import LogisticRegression

regression_model = LogisticRegression()
regression_model.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [23]:
regression_model.score(X_test, y_test)

0.7586206896551724

In [26]:
model.predict([[34, 	1, 	20.2, 	3.2, 	132, 	28, 	240 ,	6.0 ,	2.1 	,0.43 	]])

array([1])

#Random forest

In [17]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(n_estimators=30, max_depth=10, random_state=1)

random_forest.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=30, n_jobs=1,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [18]:
from sklearn.metrics import accuracy_score

y_predict = random_forest.predict(X_test)
accuracy_score(y_test, y_predict)

0.6896551724137931

In [27]:
model.predict([[34, 	1, 	20.2, 	3.2, 	132, 	28, 	240 ,	6.0 ,	2.1 	,0.43 	]])

array([1])